import { motion } from "framer-motion";
import { Globe, RefreshCw, ChevronLeft, ChevronRight, ExternalLink, Maximize2, Layout, Sliders, BarChart, Settings } from "lucide-react";
import { cn } from "../../utils/cn";

interface PreviewBrowserProps {
  viewport: "desktop" | "tablet" | "mobile";
  url: string;
}

// Separate component for the "Generated" application content
// This keeps the code clean and maintains proper JSX/TSX standards
function GeneratedAppContent() {
  const cards = [
    { title: "Real-time Analytics", description: "Monitor your application performance with AI-powered insights.", id: "card-1" },
    { title: "Performance Monitoring", description: "Stay ahead with predictive error detection and resolution.", id: "card-2" },
    { title: "Advanced Security", description: "Enterprise-grade protection with automated auditing tools.", id: "card-3" }
  ];

  return (
    <div className="min-h-full bg-[#050505] text-white font-sans overflow-y-auto custom-scrollbar">
      {/* Navigation Simulation */}
      <nav className="p-6 border-b border-white/5 flex items-center justify-between sticky top-0 bg-[#050505]/80 backdrop-blur-md z-10">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-violet-500 to-blue-500 shadow-lg shadow-violet-500/20" />
          <span className="font-bold tracking-tight text-sm md:text-base">AI Generated App</span>
        </div>
        <div className="hidden md:flex gap-6 text-[13px] text-white/40 font-semibold">
          <span className="text-white">Dashboard</span>
          <span className="hover:text-white transition-colors cursor-pointer">Analytics</span>
          <span className="hover:text-white transition-colors cursor-pointer">Settings</span>
        </div>
        <button className="px-5 py-2 rounded-xl bg-white text-black text-xs font-bold hover:bg-white/90 transition-all active:scale-95">
          Connect
        </button>
      </nav>

      {/* Hero Section Simulation */}
      <main className="p-8 md:p-12 max-w-5xl mx-auto space-y-12">
        <div className="space-y-6">
          <h1 className="text-4xl md:text-6xl font-bold leading-tight tracking-tight">
            Fastest way to build <br/>
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-violet-400 to-fuchsia-400">
              Modern Software
            </span>
          </h1>
          <p className="text-white/40 text-base md:text-lg max-w-2xl leading-relaxed">
            This interface was generated by FrameForge AI. It features responsive layouts, 
            premium glassmorphism, and optimized components refined for production environments.
          </p>
          <div className="flex items-center gap-4">
             <button className="px-6 py-3 rounded-xl bg-brand-purple text-white font-semibold text-sm hover:brightness-110 transition-all">Get Started</button>
             <button className="px-6 py-3 rounded-xl bg-white/5 border border-white/10 text-white font-semibold text-sm hover:bg-white/10 transition-all">Live Demo</button>
          </div>
        </div>

        {/* Feature Grid Simulation */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {cards.map((card) => (
            <div 
              key={card.id} 
              className="p-8 rounded-3xl bg-white/[0.03] border border-white/10 space-y-4 hover:border-brand-purple/30 transition-all group cursor-pointer"
            >
              <div className="w-12 h-12 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center text-white/40 group-hover:text-brand-purple transition-colors">
                 {card.id === 'card-1' && <BarChart className="w-5 h-5" />}
                 {card.id === 'card-2' && <Sliders className="w-5 h-5" />}
                 {card.id === 'card-3' && <Layout className="w-5 h-5" />}
              </div>
              <h3 className="font-bold text-lg">{card.title}</h3>
              <p className="text-white/40 text-sm leading-relaxed">{card.description}</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}

export function PreviewBrowser({ viewport, url }: PreviewBrowserProps) {
  return (
    <div className="flex-grow flex flex-col items-center justify-center p-6 lg:p-12 bg-[#020202] relative overflow-hidden">
      {/* Background Radiance */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(139,92,246,0.05)_0%,transparent_100%)] pointer-events-none" />
      
      <motion.div
        initial={false}
        animate={{ 
          width: viewport === "desktop" ? "100%" : viewport === "tablet" ? 768 : 375,
          height: viewport === "desktop" ? "100%" : viewport === "tablet" ? "90%" : "85%"
        }}
        transition={{ type: "spring", damping: 30, stiffness: 200 }}
        className="max-w-[1400px] w-full h-full bg-black rounded-3xl shadow-[0_40px_120px_-20px_rgba(0,0,0,0.9)] border border-white/10 overflow-hidden flex flex-col relative z-10"
      >
        {/* Browser Header Controls */}
        <div className="h-14 bg-[#0D0D0D] border-b border-white/5 flex items-center px-6 gap-6 flex-shrink-0">
          <div className="flex gap-2 flex-shrink-0">
            <div className="w-3 h-3 rounded-full bg-red-500/80 shadow-[0_0_10px_rgba(239,68,68,0.2)]" />
            <div className="w-3 h-3 rounded-full bg-yellow-500/80 shadow-[0_0_10px_rgba(234,179,8,0.2)]" />
            <div className="w-3 h-3 rounded-full bg-green-500/80 shadow-[0_0_10px_rgba(34,197,94,0.2)]" />
          </div>
          
          <div className="flex items-center gap-2 flex-shrink-0">
            <button className="p-2 rounded-xl hover:bg-white/5 text-white/20 hover:text-white transition-all">
              <ChevronLeft className="w-4 h-4" />
            </button>
            <button className="p-2 rounded-xl hover:bg-white/5 text-white/20 hover:text-white transition-all">
              <ChevronRight className="w-4 h-4" />
            </button>
            <button className="p-2 rounded-xl hover:bg-white/5 text-white/20 hover:text-white transition-all">
              <RefreshCw className="w-3.5 h-3.5" />
            </button>
          </div>

          <div className="flex-grow max-w-2xl mx-auto h-8 rounded-xl bg-black/60 border border-white/10 flex items-center px-4 gap-3 overflow-hidden shadow-inner">
             <Globe className="w-3.5 h-3.5 text-white/20" />
             <span className="text-[11px] text-white/30 truncate select-none font-mono tracking-wide">{url}</span>
          </div>

          <div className="flex items-center gap-2 flex-shrink-0">
            <button className="p-2 rounded-xl hover:bg-white/5 text-white/20 hover:text-white transition-all border border-transparent hover:border-white/10">
              <Maximize2 className="w-4 h-4" />
            </button>
            <button className="p-2 rounded-xl hover:bg-white/5 text-white/20 hover:text-white transition-all border border-transparent hover:border-white/10">
              <ExternalLink className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Dynamic Viewport Content */}
        <div className="flex-grow overflow-hidden relative bg-[#050505]">
          <GeneratedAppContent />
        </div>
      </motion.div>

      {/* Bottom Reflection Effect */}
      <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-3/4 h-32 bg-brand-purple/5 blur-[120px] pointer-events-none" />
    </div>
  );
}
